# Generated by Django 6.0.6 on 2026-06-15 18:13

import django.core.validators
import mandir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name_en', models.CharField(max_length=200)),
                ('event_name_hi', models.CharField(max_length=200)),
                ('event_time', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('bhajan', 'Bhajan Sandhya'), ('special', 'Special'), ('weekly', 'Weekly')], default='other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='image', max_length=10)),
                ('file', models.FileField(upload_to=mandir.models.upload_gallery_image_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'avi', 'mkv', 'webm'])])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
